from __future__ import annotations

from dataclasses import dataclass, field
from typing import Protocol

from simple_ar.literature.models import Paper
from simple_ar.research.contracts import SourcePlan


@dataclass(frozen=True)
class SearchQuery:
    """A source-agnostic literature search request."""

    query: str
    max_results: int = 10
    filters: dict[str, object] = field(default_factory=dict)


@dataclass(frozen=True)
class SearchResponse:
    """A source-agnostic literature search response."""

    source: str
    query: str
    papers: list[Paper]
    status: str = "ok"
    message: str = ""


class LiteratureConnector(Protocol):
    """Protocol implemented by metadata and document source connectors."""

    source_name: str

    def search(self, request: SearchQuery) -> SearchResponse:
        """Search a literature source and return normalized papers."""
        ...


def build_source_plan(
    *,
    topic: str,
    problem_markdown: str,
    config: dict[str, object],
    default_query: str,
    default_max_results: int,
) -> SourcePlan:
    """Build a V2.3 research source plan from run configuration.

    Args:
        topic: Original research topic.
        problem_markdown: Problem artifact text used for rationale only.
        config: Runtime pipeline configuration.
        default_query: Query selected by the existing search stage.
        default_max_results: Paper limit selected by the existing search stage.

    Returns:
        Source plan describing retrieval sources, queries, budget, and local
        document hints. The plan is deliberately executable but conservative:
        it records full-text intent without downloading restricted resources.
    """
    query = _string(config.get("search_query")) or default_query
    queries = _string_list(config.get("research_queries")) or [query]
    sources = _sources(config)
    mode = _mode(config.get("research_mode"))
    require_fulltext = _bool(config.get("research_use_fulltext"), False)
    allow_pdf_download = _bool(config.get("research_allow_pdf_download"), False)
    local_documents = _string_list(config.get("research_local_documents"))
    index_backend = _string(config.get("research_index_backend")) or _default_index_backend(mode)
    budget = _budget(config)
    rationale = (
        "Generated by the V2.3 source planner from the run topic, problem artifact, "
        "and search/research configuration. Full-text access is recorded as intent "
        "and does not bypass provider access rules."
    )
    if problem_markdown.strip():
        rationale += f" Problem excerpt: {problem_markdown.strip()[:240]}"
    return SourcePlan(
        queries=queries,
        sources=sources,
        max_results_per_query=default_max_results,
        mode=mode,
        require_fulltext=require_fulltext,
        allow_pdf_download=allow_pdf_download,
        local_documents=local_documents,
        cache_enabled=_bool(config.get("research_cache"), True),
        index_backend=index_backend,
        filters={"topic": topic},
        budget=budget,
        rationale=rationale,
    )


def primary_query(plan: SourcePlan) -> str:
    """Return the first non-empty query from a source plan."""
    for query in plan.queries:
        if query.strip():
            return query.strip()
    return ""


def _sources(config: dict[str, object]) -> list[str]:
    configured = _string_list(config.get("research_sources"))
    if configured:
        return configured
    if config.get("use_arxiv") is False:
        return ["fixture"]
    return ["openalex", "semantic_scholar", "arxiv"]


def _budget(config: dict[str, object]) -> dict[str, object]:
    keys = {
        "research_max_documents": "max_documents",
        "research_max_chunks": "max_chunks",
        "research_max_context_tokens": "max_context_tokens",
        "research_max_llm_calls": "max_llm_calls",
        "research_max_follow_up_queries": "max_follow_up_queries",
        "research_max_fulltext_documents": "max_fulltext_documents",
        "research_max_pdf_mb": "max_pdf_mb",
    }
    budget: dict[str, object] = {}
    for config_key, budget_key in keys.items():
        value = config.get(config_key)
        if isinstance(value, int) and not isinstance(value, bool):
            budget[budget_key] = value
    keep_raw_pdf = config.get("research_keep_raw_pdf")
    if isinstance(keep_raw_pdf, bool):
        budget["keep_raw_pdf"] = keep_raw_pdf
    parser_backend = _string(config.get("research_parser_backend"))
    if parser_backend:
        budget["parser_backend"] = parser_backend
    return budget


def _default_index_backend(mode: str) -> str:
    if mode == "standard":
        return "sqlite_fts"
    if mode == "strong":
        return "hybrid"
    return "keyword"


def _mode(value: object) -> str:
    text = _string(value)
    return text if text in {"lite", "standard", "strong"} else "standard"


def _bool(value: object, default: bool) -> bool:
    return bool(value) if isinstance(value, bool) else default


def _string(value: object) -> str:
    return value.strip() if isinstance(value, str) and value.strip() else ""


def _string_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]
